name: Collecte Météo Automatique

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collecter-meteo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4
    
    - name: Installer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Collecter les données météo
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: node weather-collector.js
    
    - name: Sauvegarder sur GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Météo Bot"
        git add meteo.json
        git diff --staged --quiet || git commit -m "📊 Données météo $(date '+%d/%m/%Y %H:%M')"
        git push
