name: Collecte Meteo Automatique

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  collecter-meteo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Recuperer le code
      uses: actions/checkout@v4
    
    - name: Installer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
    
    - name: Collecter les donnees meteo
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: node weather-collector.js
    
    - name: Sauvegarder sur GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Meteo Bot"
        git add meteo.json
        git diff --staged --quiet || git commit -m "Donnees meteo $(date '+%d/%m/%Y %H:%M')"
        git push
