name: Weather Collector

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Collect weather
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: node weather-collector.js
    - name: Save to GitHub
      run: |
        git config user.email "action@github.com"
        git config user.name "Weather Bot"
        git add meteo.json
        git diff --staged --quiet || git commit -m "Weather data $(date)"
        git push
